### ISSUE TITLE
Angular 9 error

### ISSUE THREAD

**Issue by binhdotx** [ericferreira1992/alphabet-filter#11]
When using with Angular 9, I get Renderer2 error such as this below.  Are there are any plans to upgrading the component to Angular 9?

ERROR in node_modules/alphabet-filter/alphabet-filter.component.d.ts:1:83 - error TS2724: Module '"../@angular/core/core"' has no exported member 'Renderer'. Did you mean 'Renderer2'?

**Comment by ericferreira1992** [comment]
How you may already know, Render2 is deprecated in Angular 9 because it uses the Ivy now. I will fix this as soon as possible so they don't have problems with Angular 9.

Wait, thanks.

**Comment by ericferreira1992** [comment]
@binhdotx Launched new version 1.1.0 compatible with Angular 9.
https://www.npmjs.com/package/alphabet-filter

Please run `npm update alphabet-filter`
