### ISSUE TITLE
Alphabet filter is not working properly for R letter

### ISSUE THREAD

**Issue by rjpatil** [ericferreira1992/alphabet-filter#23]
https://ericferreira1992.github.io/alphabet-filter/
here on both the examples, if I click on R letter it will shifts to P letter

**Comment by ericferreira1992** [comment]
@rjpatil  
Thanks for the feedback.
The version 1.2.0 of [alphabet-filter](https://www.npmjs.com/package/alphabet-filter) is available with that fix, just update the dependency in your Angular project. 🙂
