### ISSUE TITLE
Alphabet filter is not sorting small letters

### ISSUE THREAD

**Issue by kumarAmaragonda** [ericferreira1992/alphabet-filter#24]
Hi Team,
   Alphabet filter is not sorting small letters. Please find the below stackblitz url for reference.
 URL:: https://stackblitz.com/edit/angular-tjgpfv?file=src%2Fapp%2Fapp.component.ts

Here the small letter clients3 comes after the list i.e. at the bottom of the list.
![image](https://user-images.githubusercontent.com/18000054/93988588-879f8b80-fda6-11ea-9c57-f509c1f6e1b7.png)

Can you please help me with this.

Thanks and Regards,
 kumar.

**Comment by ericferreira1992** [comment]
@kumarAmaragonda 
Thanks for the feedback.
The version 1.2.0 of [alphabet-filter](https://www.npmjs.com/package/alphabet-filter) is available with that fix, just update the dependency in your Angular project. 🙂
