### ISSUE TITLE
Alphabet List Click doesn't move list

### ISSUE THREAD

**Issue by kumarAmaragonda** [ericferreira1992/alphabet-filter#33]
Hi, @ericferreira1992
we updated the plugin version to 1.2.1, but it is still not working, I have gone through the source code of Alphabetfilter, In Public goLetter(letter: string) method, you have used the below lines.

const letterElement = [...lettersElList].find((el: HTMLElement) => {
				const splitted = el.classList.value.split(' ');
				if (splitted.length > 0 && splitted[splitted.length - 2].includes('-')) {
        const letterClass = splitted[splitted.length - 2].split('-')[1].toUpperCase();
        debugger;
					return letterClass === letter;
				}
but in our Angular 5+ applications, we getting splitted.length as 3, as **ng-star-inserted** class appended to li element due to *ngFor, which causing the issue. Can you please look into it?

Thanks and Regards,
Kumar.

**Comment by ericferreira1992** [comment]
@kumarAmaragonda 
I fix it. Check the new version 1.2.2, and tell here if did work. Thanks.
