### ISSUE TITLE
Alphabet Filter scrolls to much fast

### ISSUE THREAD

**Issue by udayraj21** [ericferreira1992/alphabet-filter#6]
@ericferreira1992 
End users are getting irritated while they scroll the alphabet filter list by using latop touchpad and / or mouse scroll button because they hardly can stop at the particular list item. Is there any way to allow alphabet filter to get scrolled in normal way? For example, as we srcoll normal web page?

**Comment by ericferreira1992** [comment]
@udayraj21 
I create a new property named **noSmoothScroll** to disabled smooth scroll. Update to version 1.0.5, and add [noSmoothScroll]="true", so that scrolling works natively.

**Comment by ericferreira1992** [comment]
No reply. I understand that the problem has been resolved. So, topic closed!
